use_frameworks!
platform :ios, '10.0'

target 'YoutubeMediaApi_Example' do
	pod 'YoutubeMediaApi', :path => '../'
	pod 'PromiseKit', '~> 4.4'
	pod 'PromiseKit/Alamofire'
	pod 'Kingfisher', '~> 4.0'
	pod 'youtube-ios-player-helper'

  target 'YoutubeMediaApi_Tests' do
	  inherit! :search_paths
	  
	  pod 'YoutubeMediaApi', :path => '../'
	  pod 'Quick', '~> 1.2.0'
	  pod 'Nimble', '~> 7.0.2'
  end
end
