use_frameworks!

target 'YoutubeApiMedia_Example' do
  pod 'YoutubeApiMedia', :path => '../'

  target 'YoutubeApiMedia_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
